# -*- coding: utf-8 -*-
"""Copy of Aula Pratica 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRlMWh8vHlZklhbZjYz_iTqbC5jRKUdQ
"""

valor_produto = float(input('Entre com o valor desejado:'))
qtd = int(input('Entre com a quantidade desejada:'))
desc = 0 
#Siglas qtd = Quantidade de Produtos | | desc = Desconto 
if qtd <= 4: #Outra maneira if qtd < 5: / Produtos menos que 4 tem 0 de desconto 
  desc = 0.00
elif 5 <= qtd < 20: #if(qtd>= 5) and (qtd <20): Produtos de +5 e menores que 20 tem 3% de desconto
  desc = 0.03 #3% 0.03 || 100% = 1.00
elif 20 <= qtd < 100: #if(qtd>= 20) and (qtd <100):
  desc = 0.06 #6% 0.06 || 100% = 1.00
else:
  desc = 0.10 

total_sem_desc = valor_produto * qtd 
print('O valor total sem o desconto é de R$ {:.2f}'.format(total_sem_desc))
total_com_desc = total_sem_desc - total_sem_desc * desc
print('O valor total com o desconto é de R$ {:.2f}'.format(total_com_desc))